# Generated by Django 2.1.8 on 2019-06-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postlist',
            new_name='Blog',
        ),
    ]
